baseURL = "https://HRB213.github.io/herobi/"
locale = "ja"
defaultContentLanguage = "ja"
title = "herobi"

theme = ["github.com/adityatelange/hugo-PaperMod"]

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  description = "Rust製CLIツール"